axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 2.0
  y: 0.0
scale_linear_turbo:
  x: 4.0
  y: 0.0
axis_angular:
  yaw: 0
scale_angular:
  yaw: 2.0
scale_angular_turbo:
  yaw: 4.0
enable_button: 4
enable_turbo_button: 7
